name: "Version Update"
description: "GitHub Action for automated version management based on conventional commits"
author: "dragoscops"

inputs:
  branch:
    description: "The branch to commit/merge into (useful when you're maintaining multiple version branches)"
    required: false
    default: "main"
  github_token:
    description: "GitHub token for authentication"
    required: false
  pr:
    description: "Perform version update by creating a pull request"
    required: false
    default: "false"
  pr-auto-merge:
    description: "Automatically merge the pull request if it passes checks"
    required: false
    default: "false"
  pr-message:
    description: "This message will be used for the pull request"
    required: false
    default: "chore: version update"
  token:
    description: "GitHub token for actions like creating pull requests"
    required: false
    default: ${{ github.token }}
  workspaces:
    description: 'Comma-separated workspace definitions with format "path:type", e.g., ".:text,packages/node:node"'
    required: false
    default: ".:text"

# outputs:
#   changed_workspaces_info:
#     description: 'Comma-separated list of changed workspaces with format "path:type:name:version"'
#   updated_workspaces_info:
#     description: 'Comma-separated list of updated workspaces with format "path:type:name:version"'
#   version:
#     description: "The new version after update"
#   pr_number:
#     description: "Pull request number if one was created"
#   pr_url:
#     description: "Pull request URL if one was created"

runs:
  using: "node20"
  # main: 'dist/index.js'
  main: "src/index.js"

branding:
  icon: "tag"
  color: "blue"
