version: '3'

tasks:
  edit:
    cmds:
      - |
        export $(cat .env.local | grep -v '^#') && code-insiders .
    desc: "Run Bumpalicious in edit mode"

  prepare:
    cmds:
      - npm install
      - npx husky
      # https://github.com/isaacphi/mcp-language-server
      - go install github.com/isaacphi/mcp-language-server@latest
      # https://github.com/typescript-language-server/typescript-language-server
      - npm install -g typescript-language-server typescript
    desc: "Install dependencies"
