name: Bumpalicious CI

run-name: "Bumpalicious CI :: ${{ github.event_name }} (${{ github.ref_name }})"

on:
  workflow_dispatch: {}
  workflow_call: {}
  push:
    branches-ignore:
      - "test-bumpalicious-*"
    paths-ignore:
      - "test/**"
    tags-ignore:
      - "v*"
  pull_request:
    branches: [main, v1, v2, v3]
    paths-ignore:
      - "test/**"
      - package.json
      - CHANGELOG.md
      - CHANGELOG.new.md

concurrency:
  group: bumpalicious-ci-global
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

env:
  NODE_VERSION: "20"

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    if: ${{ ! contains(github.actor, '[bot]') }}
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      branch: ${{ steps.prereqs.outputs.branch }}
    steps:
      - name: Prerequisites
        id: prereqs
        run: |
          echo "branch=${{ github.head_ref || github.ref }}" >> $GITHUB_OUTPUT

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Only need last 2 commits for skip check

      - name: Setup Node with caching
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        # env:
        #   DEBUG: log:*
        run: npm run test

  tests-integration:
    name: Integration Tests
    needs: tests
    if: ${{ ! contains(github.actor, '[bot]') }}
    uses: ./.github/workflows/test.yml
    secrets: inherit

  version-bump:
    name: Version Bump
    needs:
      - tests
      - tests-integration
    if: ${{ ! contains(github.actor, '[bot]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Github App Token
        id: app-token-push
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.GH_APP_PUSH_ID }}
          private-key: ${{ secrets.GH_APP_PUSH_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout repo (using token)
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token-push.outputs.token || secrets.GH_TOKEN_PUSH }}
          fetch-depth: 0

      # - name: Increase Version
      #   id: version_step
      #   uses: ./
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN_PUSH }}
      #     workspaces: .:node
      #     branch: ${{ github.ref }}
      #     pr: true
      #     pr_version_prefix: bump_version
      #     short_tag: true
